### ISSUE TITLE
Benchmarking of `for i in seq 0 1000` is wrong

### ISSUE THREAD

**Issue by livibetter** [ryanmjacobs/bash-loops#1]
I was very surprised to read your results, although I thought you intentionally wrote `for i in seq 0 1000` in the results, even I knew it would not be the right code.

If you run `for.sh`, you can see only three lines of "hello" instead of 1000 lines. The `$i` would be `seq`, `0`, and `1000`, literally, and that's not what we want here.

The correct `for` the benchmarking should be:

``` bash
for i in $(seq 0 1000); do
```

Or

``` bash
for i in `seq 0 1000`; do
```

Furthermore, I think `:` or `true` builtin is better than `echo` in the loop, since you only want to benchmark the looping itself, so minimizing the execution on other tasks should have a better and more accurate result.

By the way, `seq 0 1000` would generate 1001 numbers, some of the scripts run 1000 iterations, others run 1001 iterations. It's a minor flaw, though should be fixed.

**Comment by ryanmjacobs** [comment]
Oops. That's a big mistake on my part. Only doing 3 iterations instead of 1000 probably skewed the results a bit... :grimacing:

Anyways, I've updated the results, and it seems that `for i in {0..1000}` is the fastest. Later, I'm going to see if it's linear for each one or maybe graph it with R.
